Add vue + vite sample
openkraken/samples pull request #10
Opened 2021-09-18 19:15 UTC by yyx990803

Main changes in config:

- Use `build --watch` during dev
- Avoid minification during dev
- Disable code splitting and chunk hashing

2021-09-18 19:17 UTC, yyx990803 commented
另外建议文档里默认推荐基于 Vite 的配置，因为以后 Vue 3 的默认推荐工具将从 Vue-CLI 转到 Vite。

2021-09-18 19:41 UTC, 0x1074 commented
Is svelte going to be supported in the future? Thanks!

2021-09-18 22:41 UTC, yyx990803 commented
@0x1074 both Kraken and Vite are framework agnostic. It's trivial to adapt this example to use Svelte, React, or any framework that works with Vite.

2021-09-19 01:37 UTC, cnryb requested changes

2021-09-19 01:37 UTC, cnryb commented on demos/hello-vue-vite/index.html
> +<script type="module" src="/src/main.js"></script>
src 目录忘记提交了吧

2021-09-19 02:06 UTC, answershuto commented
![image](https://user-images.githubusercontent.com/17812136/133913091-55eca47a-8a1b-49f7-b872-6e736845c22b.png)

跑了一下发现似乎没有 src 目录。

2021-09-19 17:43 UTC, yyx990803 commented
copy 的时候忘记了... 😅

2021-09-20 01:04 UTC, cnryb approved these changes

2021-09-22 02:32 UTC, answershuto commented
![lgtm](https://user-images.githubusercontent.com/17812136/134274232-1a2dc2c8-0aab-40f4-8bfb-6b2b0bfa3ecb.png)

2021-09-22 02:32 UTC, merged

2021-09-22 03:33 UTC, andycall commented
我们会在后面支持 ES6 Modules 来提供更好的 vite 开发体验